apiVersion: v1
kind: Namespace
metadata:
  name: c2c-opsera-vishnu-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-opsera-vishnu-deployment
  namespace: c2c-opsera-vishnu-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:a8b797e6d9bac673e6c625747b276cb1ada65d6d

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-opsera-vishnu-label
  name: c2c-opsera-vishnu-service
  namespace: c2c-opsera-vishnu-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---